#!/bin/bash
set +ex

echo "ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET"
echo "PROD_DBHOST=$PROD_DBHOST"
echo "PROD_DBPORT=$PROD_DBPORT"
echo "PROD_DBNAME=$PROD_DBNAME"
echo "PROD_DBUSER=$PROD_DBUSER"
echo "PROD_DBPASS=$PROD_DBPASS"
echo "NEXMO_KEY=$NEXMO_KEY"
echo "NEXMO_SECRET=$NEXMO_SECRET"
echo "NEXMO_ID=$NEXMO_ID"