version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies in car share server
          command: |
            cd src/Backend/carshare/
            npm install
      - run:
          name: Install dependencies in authentication server
          command: |
            cd src/Backend/authServer/
            npm install


jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: CarShareTest
    steps:
      - checkout
      - install_deps
    
  unit-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: CarShareTest
    steps:
      - checkout
      - install_deps
      - run:
          name: run car share server unit tests  
          command: |
            cd src/Backend/carshare/
            mkdir -p ../test-output
            npm run unit-test
      - store_test_results:
          path: src/Backend/carshare/test-results.xml
    
  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: CarShareTest
    steps:
      - checkout
      - install_deps
      - run:
          name: run authentication server integration tests
          command: |
            cd src/Backend/authServer/
            npm run integration-test
  
  package:
    machine: true
    environment:
      NODE_ENV: production
    steps:
      - checkout

      - run:
          name: Setup
          command: |
            mkdir -p artifacts

      - run:
          name: Config dot env
          command: |
            cd infra
            sh prod.env.sh > .env
            cp .env ../src/Backend/authServer
            cp .env ../src/Backend/carshare
      
      - run: 
          name: Compress backend applications
          command: |
            cd src
            zip -r server Backend
            mv  server.zip ../artifacts/server.zip

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts

      - store_artifacts:
          path: artifacts/server.zip
  
  deploy:
    machine: true
    steps:
      - checkout

      - attach_workspace:
          at: ./

      - add_ssh_keys:
          fingerprints:
            - "b1:cf:89:18:4e:f2:2b:2b:b6:d2:5c:2d:81:d4:a9:8c"
          
      - run:
          name: Run ansible playbook to deploy the app
          command: |
            cd ansible
            sudo sh run_ansible.sh

            
workflows:
    build-test-package-deploy:
      jobs:
        - build
        - unit-tests:
            requires:
              - build
        - integration-tests:
            requires:
              - build
        - package:
            requires:
              - unit-tests
              - integration-tests
        - approval:
            type: approval
            requires:
              - package
            filters:
              branches:
                only: f/deploy_test
        - deploy:
            requires:
              - approval