version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            cd src/Backend/carshare/
            npm install


jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: CarShareTest
    steps:
      - checkout
      - install_deps
    
  unit-tests:
    docker:
      - image: circleci/node:lts
    environment:
      MOCHA_FILE: "./test-output/unit-result.xml"
    steps:
      - checkout
      - install_deps
      - run:
        name: run unit tests
        command: |
          cd src/Backend/carshare/
          mkdir test-output
          npm run unit-test
            
workflows:
    build-and-test:
      jobs:
        - build
        - unit-tests:
            requires:
              - build