version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies in car share server
          command: |
            cd src/Backend/carshare/
            npm install
      - run:
          name: Install dependencies in authentication server
          command: |
            cd src/Backend/authServer/
            npm install


jobs:
  build:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: CarShareTest
    steps:
      - checkout
      - install_deps
    
  unit-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: CarShareTest
    steps:
      - checkout
      - install_deps
      - run:
          name: run car share server unit tests  
          command: |
            cd src/Backend/carshare/
            mkdir -p ../test-output
            npm run unit-test
      - store_test_results:
          path: src/Backend/carshare/test-results.xml
    
  integration-tests:
    docker:
      - image: circleci/node:lts
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: CarShareTest
    steps:
      - checkout
      - install_deps
      - run:
          name: run authentication server integration tests
          command: |
            cd src/Backend/authServer/
            npm run integration-test
  
  package:
    machine: true
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - run:
          name: Config dot env
          command: |
            cd infra
            sh prod.env.sh > .env
            cp .env ../src/Backend/authServer
            cp .env ../src/Backend/carshare
      
      - run: 
          name: Compress backend applications
          command: |
            cd src
            zip -r backend server

      - store_artifacts:
          path: src/server.zip

            
workflows:
    build-and-test:
      jobs:
        - build
        - unit-tests:
            requires:
              - build
        - integration-tests:
            requires:
              - build
        - package:
            requires:
              - unit-tests
              - integration-tests